### ISSUE TITLE
agi18n command not working.

### ISSUE THREAD

**Issue by awaistariq** [angelolloqui/AGi18n#10]
Hello.
I am unable to execute agi18n command after installing the command line tool.
Please have a look at attached screen shot.
![screen shot 2014-03-18 at 9 58 07 am](https://f.cloud.github.com/assets/3714825/2445124/bb4fc0ea-ae6a-11e3-9dd5-a025cf5ac3e2.png)

**Comment by kishore4a2** [comment]
How do i install manually? can you please tell me.

**Comment by nishitMishraWynk** [comment]
I cannot install agi18n. Man you gotta help us here

**Comment by angelolloqui** [comment]
I am not actively supporting this tool anymore but if you give me more info I might find the issue. Nevertheless, the tool does nothing that you can not do by combining the existing Xcode utilities and some scripts

**Comment by nishitMishraWynk** [comment]
I **manually moved** "genxibstrings" and "agi18n" from **'/bin'** directory of your pod to **"/usr/local/bin"** and ran the "curl -L https://raw.github.com/angelolloqui/AGi18n/master/bin/install.sh | sh" command It worked.

I did it because running "curl -L https://raw.github.com/angelolloqui/AGi18n/master/bin/install.sh | sh" and  "sudo curl -L https://raw.github.com/angelolloqui/AGi18n/master/bin/install.sh | sh" directly on terminal was not working.

But now after installing "agi17n" and "genxibstrings" when i use "agi18n" from terminal then this comes-

**0 languages detected: 


* DONE *
AGi18n finished internazionalizing correctly.
Remember to use the Localizable.strings files as UTF-16LE into your XCode project**

But I have two languages in my app.

**Comment by angelolloqui** [comment]
Well, if you check the code you can see that the languages come from this:

```
current_dir = File.dirname(__FILE__)
languages = Dir["*.lproj"]
puts "#{languages.length} languages detected: #{languages.join(', ')}"
```
So, if it is showing 0 is because you have no .lproj on that directory. Check the directory you are running from and that the directory files with that extension are contained in there

**Comment by nishitMishraWynk** [comment]
Issues- 

4 languages detected: en.lproj, te.lproj, Base.lproj, hi.lproj

Internazionalizing en.lproj...
Executing `genstrings -a -o en.lproj **/*.{h,m,mm,swift}`
genstrings: error: failed to read input file 
Executing `/usr/local/bin/genxibstrings -a -o en.lproj **/*.{xib,nib,storyboard}`
Removing duplicates from en.lproj/Localizable.strings

Internazionalizing te.lproj...
Executing `genstrings -a -o te.lproj **/*.{h,m,mm,swift}`
genstrings: error: failed to read input file 
Executing `/usr/local/bin/genxibstrings -a -o te.lproj **/*.{xib,nib,storyboard}`
Removing duplicates from te.lproj/Localizable.strings

Internazionalizing Base.lproj...
Executing `genstrings -a -o Base.lproj **/*.{h,m,mm,swift}`
genstrings: error: failed to read input file 
Executing `/usr/local/bin/genxibstrings -a -o Base.lproj **/*.{xib,nib,storyboard}`
Removing duplicates from Base.lproj/Localizable.strings

Internazionalizing hi.lproj...
Executing `genstrings -a -o hi.lproj **/*.{h,m,mm,swift}`
genstrings: error: failed to read input file 
Executing `/usr/local/bin/genxibstrings -a -o hi.lproj **/*.{xib,nib,storyboard}`
Removing duplicates from hi.lproj/Localizable.strings


* DONE *
AGi18n finished internazionalizing correctly.
Remember to use the Localizable.strings files as UTF-16LE into your XCode project


also i tried using it in another project... only the strings of storyboard files are being generated.

**Comment by angelolloqui** [comment]
Genstrings is an Xcode command line utility. Make sure it is installed and works before running the agi18n utility. Try running that command directly and check if you have any error in it
